# Name of our action
name: 'Chromatic'
# The event that will trigger the action
on: push

# What the action will do
jobs:
  test:
   # The operating system it will run on
   runs-on: ubuntu-latest
   # The lists of steps that the action will go through
   steps:
     - uses: actions/checkout@v1
     - run: yarn
     # Adds chromatic as a step in the workflow
     - uses: chromaui/action@v1
     # Options required for Chromatic's Github Action
       with:
        # Chromatic projectToken,
          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          token: ${{secrets.GITHUB_TOKEN}}
